<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Authors>pyreymo</Authors>
    <Version>0.1.0</Version>
    <Description>FFXIV native G-buffer drawing for Dalamud plugins</Description>
    <PackageProjectUrl>https://github.com/pyreymo/ffxiv-underpaint</PackageProjectUrl>
    <RepositoryUrl>https://github.com/pyreymo/ffxiv-underpaint.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <Use_DalamudPackager>false</Use_DalamudPackager>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
  </ItemGroup>
</Project>
